### ISSUE TITLE
Chapter 2: What is "one confirmation"?

### ISSUE THREAD

**Issue by biafra23** [bitcoinbook/bitcoinbook#121] opened 2014-08-24 20:27 UTC
In https://github.com/aantonop/bitcoinbook/blob/develop/ch02.asciidoc#mining-transactions-in-blocks the text says: 

"One block mined on top of the one containing the transaction is called "one confirmation" for that transaction."

According to https://en.bitcoin.it/wiki/Confirmation and http://en.bitcoinwiki.org/Transaction_confirmation the first confirmation is created by the block that contains the transacion. Is this just a matter of opinion or is there an authoritative source for what "one confirmation" is? Is it the same as "first confirmation"?

**Comment by enderminh** [comment] 2014-08-24 21:15
Thanks for the report. This is actually a dupe of issue #18 and the fix for this is already proposed in pull request #114 (which I haven't merged in yet, as I wanted to get some confirmation from Andreas first one some other changes in that large pull request).

Bottom line is that the text is currently incorrect; The first block a transaction is mined in is considered the first confirmation.

**Closed as completed by enderminh** 2014-08-24 21:15 UTC
