### ISSUE TITLE
Ch 03 - Add link for obtaining most recent blockchain size

### ISSUE THREAD

**Issue by matkirch** [bitcoinbook/bitcoinbook#467] opened 2018-01-10 21:05 UTC
In the section Running a Bitcoin Core Node of Chapter 03, the text reads:

> As of late 2016, a full-index node needs 2 GB of RAM and 125 GB of disk space so that it has room to grow. 

Since the size changes rapidly, I would suggest adding a footnote with a link to https://blockchain.info/charts/blocks-size (or some other frequently updated page) so that readers can find the very latest size requirement (estimate).

**Comment by montvid** [comment] 2018-01-11 13:25
The link does not work for me on firefox - 400: Unknown language (lt)

**Comment by matkirch** [comment] 2018-01-12 19:05
Not sure, still works for me... but it could be any site that shows an updated blockchain size, doesn't have to be this specific one. Just something to refer reader to for up-to-the-minute size info.

**Comment by aantonop** [comment] 2018-02-03 04:37
duplicate of #386

**Closed as completed by aantonop** 2018-02-03 04:37 UTC
Labels: suggested content

**Comment by aantonop** [comment] 2018-03-03 20:41
Thanks fixed 3cff672
