### ISSUE TITLE
Ch. 02 Difficulty picture mbc2_0209 incorrect 

### ISSUE THREAD

**Issue by montvid** [bitcoinbook/bitcoinbook#471] opened 2018-01-12 09:59 UTC
As the name "Figure 9. Alice’s transaction included in block #277316" suggests that it is about Alice tx so the Difficulty arrow should start from block 277316 as the difficulty to reverse Alice tx starts from that block, see here https://en.bitcoin.it/wiki/Confirmation

**Comment by wbnns** [comment] 2020-05-01 20:06
@montvid 

Thank you. Closing this since it is a duplicate of #470.

**Comment by montvid** [comment] 2020-05-01 20:14
#470 and #471 are two errors in the same picture. You have to fix both in the picture it is not a duplicate if you look at the picture yourself https://howieliux.github.io/assets/others/Mastering_bitcoin/images/mbc2_0209.png

**Comment by wbnns** [comment] 2020-05-01 20:18
@montvid Apologies for missing this. Reopening; thanks for letting me know.

**Comment by montvid** [comment] 2020-05-01 20:21
Thanks for fixing the book. Yeah, the picture is an epic fail. 🤣

**Closed as completed** 2021-03-11 11:16 UTC
Labels: image issue
