### ISSUE TITLE
Incorrect address in Figure 3, Chapter 4.

### ISSUE THREAD

**Issue by erikwam** [bitcoinbook/bitcoinbook#24] opened 2014-05-04 18:57 UTC
In "Figure 3 Type-2 Chained Deterministic Keys..." : 
The same 256-bit hash and bitcoin address is shown for both index 0 and index 1.

**Comment by enderminh** [comment] 2014-05-05 01:33
This is a duplicate of Issue #22 . Closing.

**Closed as completed by enderminh** 2014-05-05 01:33 UTC
